routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::post('/categories', [CategoryController::class, 'create'])->name('categories.create');
Route::post('/categories/{id}', [CategoryController::class, 'destroy'])->name('categories.destroy');

Route::resource('post', 'App\Http\Controllers\PostController');

app/Models/Categories.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categories extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
    ];

}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'content',
        'category_id',
        'user_id',
    ];
    // protected $casts = [
    //     'categories' => 'array',
    // ];

    public function category()
    {
        return $this->belongsTo(Categories::class, 'category_id', 'id');
    }
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
    public static function getPostUserModel($id)
    {
        $post = Post::orderBy('created_at', 'desc')->where('user_id', $id)->paginate(10);
        return $post;
    }
    public static function getAllPostModel()
    {
        $post = Post::orderBy('created_at', 'desc')->paginate(10);
        return $post;
    }
    public static function getPostIdModel($id)
    {
        $post = Post::where('id', $id)->first();
        return $post;
    }
    public static function getPostCategories()
    {
        $categories = Categories::orderBy('created_at', 'desc')->get();
        return $categories;
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Categories;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $categories = Categories::get();
        return view('categories', ['categories' => $categories]);
    }
    public function create(CategoryRequest $request)
    {
        Categories::create(['title' => $request->title]);
        return redirect('categories');
    }
    public function destroy($id)
    {
        DB::table('categories')->delete($id);
        return redirect('categories');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;

class HomeController extends Controller
{
    public function index()
    {
        $posts = Post::getAllPostModel();
        return view('home', ['posts' => $posts]);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        // $posts = Post::paginate(10);
        $categories = Post::getPostCategories();
        $post = Post::getPostUserModel(auth()->user()->id);

        return view('post', ['categories' => $categories, 'posts' => $post]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        // $arrCategories = explode(',', $request->categories);
        Post::create(array_merge($request->all(), ['user_id' => auth()->user()->id]));
        return redirect()->back()->with('success', 'Add post successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Post::getPostCategories();
        $invidulePost = Post::getPostIdModel($id);
        $post = Post::getPostUserModel(auth()->user()->id);

        return view('post', ['categories' => $categories, 'posts' => $post, 'edit' => $id, 'ipost' => $invidulePost]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        $post = Post::findOrFail($id);
        $post->update((array_merge($request->all(), ['created_at' => Carbon::now()])));
        return redirect()->route('post.index')->with('success', 'Update post successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $postid = Post::findOrFail($id);
        $postid->delete();

        return redirect('post')->with(['success' => "Delete successfully"]);
    }
}

resources/views/categories.blade.php
@extends('layouts.app')
@section('content')



<div class="container-md">
    <div class="row">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    <h5> Create New Categories</h5>
                </div>
                <div class="card-body">
                    <form method="POST"  action="{{ route('categories.create') }}" >
                      @csrf
                        <label for="title" class="form-label" >Title of categies</label>
                        <input type="text" required id="title" class="form-control" name="title" placeholder="title">
                        <input type="submit" class="btn btn-primary mt-2" value="Create New categories">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h5>All Categories</h5>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">title</th>
                            <th scope="col">action</th>                       
                          </tr>
                        </thead>
                        <tbody>
                         
                          @foreach ($categories as $category )
                          <tr>
                            <th scope="row">{{$loop->index + 1}}</th>
                            <td>{{$category->title}}</td>
                            <td >
                              <form action="{{route('categories.destroy' , $category->id)}}" method="POST" >
                                @csrf
                                <input class="btn btn-danger" value="Delete" type="submit" />  
                              </form>
                            </td>                   
                          </tr>                    
                          @endforeach                
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @foreach ($posts as $post)
            <div class="col-lg-8">
                <h1 class="mt-4">{{ $post->title }}</h1>
                <p class="lead">
                    by
                    <a href="#">{{ $post->user->name }}</a>
                </p>
                <hr>
                <p>Posted on {{ date('d-M-o h:i:s', strtotime($post->created_at)) }}</p>
                <p class="badge bg-primary text-white">{{ $post->category->title }}</p>
                <hr>
                <p class="lead">{{ $post->content }}</p>
                <hr>
            </div>
        @endforeach
        @if (count($posts) == 0)
            <div class="alert alert-primary" role="alert">
                Post not found please login publish and the first post ! <a href="{{ route('post.index') }}"
                    class="alert-link">Try
                    now</a>.
            </div>
        @endif
        <div class="d-flex m-3"> {{ $posts->links() }}</div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ asset('js/script.js') }}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->

                    <ul class="navbar-nav mr-auto mt-1">
                        @if (Request::url() === route('categories'))
                            <li class='nav-item active'><a class=" nav-link"
                                    href="{{ route('categories') }}">Categories</a></li>
                        @else
                            <li class='nav-item'><a class=" nav-link" href="{{ route('categories') }}">Categories</a>
                            </li>
                        @endif
                        @if (Request::url() === route('post.index'))
                            <li class="nav-item active"><a class="nav-link" href="{{ route('post.index') }}">Publish
                                    post</a>
                            </li>
                        @else
                            <li class="nav-item"><a class="nav-link" href="{{ route('post.index') }}">Publish
                                    post</a>
                            </li>
                        @endif


                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/post.blade.php
@extends('layouts.app')
@section('content')

    <div class="container-md">
        <div class="row">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-header">
                        <h5>All Post</h5>
                    </div>
                    <div class="card-body">
                        @foreach ($posts as $post)
                            <div class="list-group">
                                <a class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">{{ $post->title }}</h5>
                                        <small>{{ date('d-M-o h:i:s', strtotime($post->created_at)) }}</small>
                                    </div>
                                    <p class="mb-1 ellipsis div-list">{{ $post->content }}</p>
                                    <div class="d-flex mt-2">
                                        <form action="{{ route('post.edit', $post->id) }}" style="z-index: 100">
                                            <button class="btn btn-primary"><i class="fas fa-edit"></i></button>
                                        </form>

                                        <form action="{{ route('post.destroy', $post->id) }}" method="POST">
                                            @csrf
                                            @method("DELETE")
                                            <button class="btn btn-danger ml-1">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </a>
                            </div>
                        @endforeach
                        @if (count($posts) === 0)
                            <div class="alert alert-primary" role="alert">
                                You 've never published your post yet
                            </div>
                        @endif
                    </div>
                </div>

            </div>
            <div class="col-md-5">
                <div class="card">
                    <div class="card-header d-flex align-item-center">
                        <h5>
                            @if (!empty($edit))
                                Update
                            @else
                                Upload new
                            @endif
                            post
                        </h5>
                    </div>
                    <div class="card-body">
                        <form action="{{ !empty($ipost) ? route('post.update', $ipost->id) : route('post.store') }}"
                            method="POST">
                            @if (!empty($ipost))
                                @method('PUT')
                            @else
                                @method('POST')
                            @endif
                            @csrf
                            @if (session()->has('success'))
                                <div class="alert alert-success">
                                    {{ session()->get('success') }}
                                </div>
                            @endif
                            <label for="title" class="label-control">Title</label>
                            <textarea type="text" id="title" class="form-control" name="title"
                                required>{{ !empty($ipost) ? $ipost->title : '' }}</textarea>
                            <label for="content" class="label-control">Content</label>
                            <textarea name="content" class="form-control" id="content" cols="30" rows="5"
                                required>{{ !empty($ipost) ? $ipost->content : '' }}</textarea>
                            <label for="categories">Categoies</label>
                            <select class="form-control" id="categories" name="category_id" required>
                                <option value="">----Choose categories----</option>
                                @foreach ($categories as $category)
                                    @if (!empty($ipost))
                                        @if ($ipost->category->title === $category->title)
                                            <option value="{{ $category->id }}" selected>{{ $category->title }}
                                            </option>
                                        @else
                                            <option value="{{ $category->id }}">
                                                {{ $category->title }}
                                            </option>
                                        @endif
                                    @else
                                        <option value="{{ $category->id }}">
                                            {{ $category->title }}
                                        </option>
                                    @endif

                                @endforeach
                            </select>
                            @if (!empty($ipost))
                                <input type="submit" class="btn btn-primary mt-2" value="Update">
                                <a href="{{ route('post.index') }}" class="btn btn-secondary mt-2"> Back</a>
                            @else
                                <input type="submit" class="btn btn-primary mt-2" value="Add">
                            @endif
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>


@endsection